services:
  maindb:
    image: postgres
    container_name: maindb
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "admin"
    ports:
      - 5432:5432
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
#   maindb:
#     image: mongo:latest
#     container_name: maindb
#     restart: always
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: password
#     ports:
#       - 27017:27017

# (OPTIONAL) mongo express
#CMD -> http://localhost:8081
# mongo-express:
#   image: mongo-express
#   container_name: mongo-express
#   restart: always
#   ports:
#     - 8081:8081
#   environment:
#     ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
#     ME_CONFIG_MONGODB_SERVER: "maindb"
#     ME_CONFIG_BASICAUTH_USERNAME: "root"
#     ME_CONFIG_BASICAUTH_PASSWORD: "password"
#     ME_CONFIG_MONGODB_ADMINUSERNAME: root
#     ME_CONFIG_MONGODB_ADMINPASSWORD: password
#     ME_CONFIG_MONGODB_ENABLE_ADMIN: true
